### PR TITLE
Use java nio to fix broken symlink

### LINKED ISSUE #164: Broken npm symlink: Unable to call npm in scripts property
Gradle's tartree does not keep symbolic links. Therefore the symbolic link to npm got lost. This leads to the inability to use npm in the scripts property.

See issue: https://issues.gradle.org/browse/GRADLE-2844

### PR DESCRIPTION
**Pull request by s0x**
This fixes #164

### CODE REVIEW

**Comment by srs** [comment]
Thanks for the pull. Checking it now ;-)

**Comment by cbornet** [comment]
Does it work for a npm specified with npmVersion (not bundled with node) ?

**Comment by s0x** [comment]
That is actually a different issue, which has been resolved by one of the latest versions. This fix does not change any behavior but doesn't use gradles tar plugin which does not support symlinks.

**Comment by cbornet** [comment]
It's probably another issue but it has not been fixed (see #134) and it has the same initial cause (https://github.com/srs/gradle-node-plugin/commit/00cc0c899fb7cb768696c888d60884656cf6f4ed) so I was hoping it would solve it...

**Comment by s0x** [comment]
Oh I see ... actually #134 would be fixed by this change

**Comment by cbornet** [comment]
For the npm bundled with node if I understand well but not for the separately donwloaded npm. Is that correct ?

**Comment by s0x** [comment]
That's correct. I'll have a look on that tomorrow and try to find a solution for that issue as well

**Comment by cbornet** [comment]
Cool ! Thanks !

**Comment by cbornet** [comment]
@s0x Does it also work on Windows ?

**Comment by s0x** [comment]
This does not change anything on the windows installation, since this is handled separately. Is this broken on windows as well?

**Comment by cbornet** [comment]
I don't know. I use Linux. But I need it to work on Windows.

**Comment by s0x** [comment]
Same here.
If there is an issue on windows, please create a issue for that. This discussion does not relate to the MR

**Comment by s0x** [comment]
@srs: Is there anything which prevents you from merging this?

**Comment by srs** [comment]
Not sure if this will work on every installation since it's executing the `tar` command (instead of using the pure-java version). But I assume that `tar` is always available?

**Comment by s0x** [comment]
It seems that there is no pure-java version of it. The other option would be to not use the symlink at all. I'm working on it atm.

**Comment by s0x** [comment]
@srs I fixed the symlink using java nio. I guess that is the best option we have

**Comment by srs** [comment]
Nice one! Thanks. Now I haven no more concerns. Will pull this tomorrow and a lot of other PR's.

**Pull request merged**
