### PR TITLE
Install Yarn without npm

### LINKED ISSUE #175: Yarn: add support for preferred yarn installation method
Installing yarn through npm produces the warning: "It is recommended to install Yarn using the native installation method for your environment"
As yarn itself is a replacement for npm, it would be nice to have yarn installed without relying on npm. What would also get rid of the annoying warning :)

Pinging @kaitoy to get his input on this.

Thanks for the great work!
Alberto

### PR DESCRIPTION
**Pull request by komu**
Download the prepackaged Yarn distribution directly from yarnpkg.com
and extract it into yarnDir.

Fixes #175

---
This change is [Reviewable](https://reviewable.io/reviews/srs/gradle-node-plugin/186)

### CODE REVIEW

**Comment by srs** [comment]
I think we should do it like we do node-download so we can use the already existing dependency model in Gradle.

**Comment by komu** [comment]
Yes, that seems like the right thing to do. I'll update the PR.

**Comment by srs** [comment]
Thanks! That would be really nice.

**Comment by komu** [comment]
It didn't go as smoothly as I thought it would.

I followed the code in `SetupTask` and added an Ivy-repository for Yarn and tried to resolve, but that fails:

```
   > Could not resolve org.yarnpkg:yarn:0.18.0.
     Required by:
         project :scheduling-frontend
      > Could not resolve org.yarnpkg:yarn:0.18.0.
         > Could not get resource 'https://yarnpkg.com/downloads/0.18.0/yarn-v0.18.0.tar.gz'.
            > Could not HEAD 'https://yarnpkg.com/downloads/0.18.0/yarn-v0.18.0.tar.gz'. Received status code 403 from server: Forbidden
```

Problem is that `https://yarnpkg.com/downloads/0.18.0/yarn-v0.18.0.tar.gz` redirects to `https://github.com/yarnpkg/yarn/releases/download/v0.18.0/yarn-v0.18.0.tar.gz` which itself redirects to `https://github-cloud.s3.amazonaws.com/releases/...`. 

Either Github presigns S3 HEAD requests incorrectly or S3 does not support presigned HEAD requests at all.

Why Gradle itself does HEAD before GET? I have no idea.

Anyway, it seems that this is a dead end for the time being.

**Comment by mangan77** [comment]
This is a really good improvement to the plugin (even if I really would like to see a separate plugin all together)! Maybe you should merge it @srs and then improve it as it seems to be a problem with the Ivy part?

**Comment by cdeng** [comment]
While adding this awesome feature, could you please also add the ability to set the URL for fetching the Yarn distributions just like what you have for node?  We are fetching all installation packages from Nexus.  Thanks!

**Comment by kucharzyk** [comment]
Any plans about merging this pull request?

**Comment by j-baker** [comment]
Hey, I'd like to +1 getting this merged. Happy to do any required fix-up work.

We've been having issues where Yarn is breaking because the NPM dependency doesn't have a shrinkwrap, so its dependencies can break it.

This means that it might break from time to time for fairly unspecified reasons.

It'd be great to use the recommended download approach (the tar).

**Comment by alkemist** [comment]
> Either Github presigns S3 HEAD requests incorrectly or S3 does not support presigned HEAD requests at all.

It's the former.

> Why Gradle itself does HEAD before GET? I have no idea.

It does this to get the checksum/etag if advertised. It then tries to reuse any local files that have the same checksum. This is quite effective in many cases, where the same file gets published with a different name (e.g. incrementing development snapshots). There's no way to turn it off unfortunately. 

So, GitHub need to fix on there end or the binaries need to be pulled from somewhere else.

**Comment by kacpak** [comment]
Is there any progress on this? If there is a problem with official yarn links right now, it could at least be implement with setting desired URL's for fetching yarn (like for node right now).  
That way this could be used with own infrastructure. We would greatly benefit from that.

**Pull request closed without merging**
