### PR TITLE
allow node modules to be used when calling npm_run

### PR DESCRIPTION
**Pull request by jmcampanini**
this also means if:

- a local NPM is configured in gradle
- a shrinkwrap is included
- the npm package is not included in the shrinkwrap/package.json

then the build should fail with a helpful message.

### CODE REVIEW

**Comment by jmcampanini** [comment]
sorry, updated this to correctly fix the bug + included a helpful error message when the user mis-configures their build

**Comment by jmcampanini** [comment]
womp. i'm using a bad shrinkwrap. fixing that now :(

**Comment by srs** [comment]
Thanks. Nice work. Just get the build to go green and I will be happy to pull it :-)

**Comment by jmcampanini** [comment]
fixed. it does increase the build time by a bit, since it actually npm installs things :cry: maybe a future commit can pick smaller packages to cut this down.

**Comment by jmcampanini** [comment]
how long does the appveyor queue usually take? :-\

**Comment by srs** [comment]
Appveyor takes a long time as you have noticed. But it's critical for testing on windows.

**Comment by jmcampanini** [comment]
cool. it passed :-D let me know if there's anything else i can do for this PR.

when do you think a new release (`0.13`?) can be cut?

**Comment by srs** [comment]
Not sure when 0.13 will be out, but will try to get it out right after the weekend. Next version after 0.13 will probably be numbered 1.0 since I will merge node/grunt/gulp plugins.

**Comment by jmcampanini** [comment]
sounds good. thank you! :)

**Comment by jmcampanini** [comment]
ping

**Comment by srs** [comment]
Sorry about this. Been too occupied with other stuff, but picking this up again now.

**Pull request merged**
